// 栄養学・暗記カード（2026年度）
window.FLASHCARD_DB = window.FLASHCARD_DB || {};
window.FLASHCARD_DB.nutrition = [
  { id: 1, question: "栄養とは何か。", answer: "生体が外界から栄養素を取り入れ、生命活動に利用すること。", explanation: "栄養学では、栄養素の種類や役割、欠乏症などを扱う。" },
  { id: 2, question: "代謝とは何か。", answer: "生体内における物質の化学反応。", explanation: "栄養素がエネルギーや体の構成成分に変化することも含まれる。" },
  { id: 3, question: "栄養素とは何か。", answer: "ヒトが代謝を営むために外界から体内へ摂取する物質。", explanation: "栄養素は食物に含まれ、食物を摂取することで得られる。" },
  { id: 4, question: "栄養素は大きく何種類に分けられるか。", answer: "5種類。", explanation: "糖質（炭水化物）、脂質、たんぱく質、ビタミン、ミネラル（無機質）。" },
  { id: 5, question: "5大栄養素を答えよ。", answer: "糖質、脂質、たんぱく質、ビタミン、ミネラル（無機質）。", explanation: "資料では栄養素をこの5つに大別している。" },
  { id: 6, question: "三大栄養素とは何か。", answer: "糖質、脂質、たんぱく質。", explanation: "体内で燃焼してエネルギーを作り出す栄養素。" },
  { id: 7, question: "糖質・脂質・たんぱく質は何と呼ばれるか。", answer: "熱量素またはエネルギー産生栄養素。", explanation: "体内で燃焼してATPを作り出すことができる。" },
  { id: 8, question: "ATPとは何か。", answer: "アデノシン三リン酸。", explanation: "三大栄養素が体内で燃焼して作り出すエネルギーに関係する物質。" },
  { id: 9, question: "カロリー（kcal）は何から算出されるか。", answer: "糖質・脂質・たんぱく質の合計。", explanation: "資料では三大栄養素の合計でカロリーを算出するとしている。" },
  { id: 10, question: "栄養素は何に含まれているか。", answer: "食物。", explanation: "ヒトは食物を摂取することで栄養素を得ている。" },
  { id: 11, question: "Stuntingとは何か。", answer: "年齢に対して低身長。", explanation: "資料では成長が阻害されることとして示されている。" },
  { id: 12, question: "Wastingとは何か。", answer: "身長に対して低体重。", explanation: "資料では痩せ・消耗が起こることとして示されている。" },
  { id: 13, question: "Overweightとは何か。", answer: "身長に対して体重が過大。", explanation: "資料では過剰栄養も含まれる栄養問題として示されている。" },
  { id: 14, question: "Malnutritionとは何か。", answer: "栄養不良。", explanation: "Stunting、Wasting、Overweightなどを含む栄養上の問題として扱われている。" },
  { id: 15, question: "世界の5歳未満児について、2024年時点の代表的な栄養問題を3つ答えよ。", answer: "Stunting、Wasting、Overweight。", explanation: "資料に示された3つの代表的な栄養問題。" },
  { id: 16, question: "クワシオルコルの主な原因は何か。", answer: "総エネルギーに加え、特にたんぱく質の欠乏。", explanation: "資料では特にたんぱく質の欠乏が特徴として示されている。" },
  { id: 17, question: "クワシオルコルの典型的な症状は何か。", answer: "腹部症状の膨張。", explanation: "資料に典型的な症状として記載されている。" },
  { id: 18, question: "マラスムスとは何か。", answer: "総エネルギーの不足によるエネルギー欠乏症。", explanation: "資料では総エネルギー不足が原因として示されている。" },
  { id: 19, question: "マラスムスの典型的な症状は何か。", answer: "著しい体重減少を伴う衰弱。", explanation: "資料に典型的な症状として記載されている。" },
  { id: 20, question: "生活習慣病とは何か。", answer: "食習慣、運動習慣、休養、喫煙、飲酒などの生活習慣が発症・進行に関与する疾患群。", explanation: "資料では生活習慣との関係から定義されている。" },
  { id: 21, question: "生活習慣病は以前、何と呼ばれていたか。", answer: "成人病。", explanation: "加齢とともに発症・進行すると考えられていたため、かつては成人病と呼ばれていた。" },
  { id: 22, question: "「成人病」が「生活習慣病」に変更されたのは何年か。", answer: "1996年。", explanation: "若い人でも発症し、子どもの頃からの生活習慣の蓄積が関係することが分かったため。" },
  { id: 23, question: "生活習慣病の発症のベースに関与することが多いものは何か。", answer: "肥満。", explanation: "資料では、発症のベースに肥満が関与している場合が多いとされている。" },
  { id: 24, question: "メタボリックシンドロームは生活習慣病の何とされているか。", answer: "予備軍。", explanation: "資料では生活習慣病の予備軍と説明されている。" },
  { id: 25, question: "日本人の食事摂取基準とは何か。", answer: "健康の保持・増進、生活習慣病の予防を目的に、エネルギーと各栄養素の1日当たりの摂取量の基準を示したもの。", explanation: "厚生労働省が示す基準。" },
  { id: 26, question: "日本人の食事摂取基準は何を対象とするか。", answer: "エネルギー及び各栄養素の摂取量。", explanation: "1日当たりの基準として示されている。" },
  { id: 27, question: "日本人の食事摂取基準は何年ごとに改定されるか。", answer: "5年ごと。", explanation: "資料では厚生労働省が5年ごとに改定するとされている。" },
  { id: 28, question: "日本人の食事摂取基準2025年版は何年まで使用されるか。", answer: "2029年まで。", explanation: "資料に2025年版は2029年まで使用と記載されている。" },
  { id: 29, question: "食事摂取基準2025年版の目的に含まれるものは何か。", answer: "健康の保持・増進、欠乏・過剰摂取の回避、生活習慣病の発症・重症化予防、生活機能の維持・向上。", explanation: "資料に示された2025年版の対応範囲。" },
  { id: 30, question: "食事摂取基準を示している機関はどこか。", answer: "厚生労働省。", explanation: "資料では厚生労働省が5年ごとに改定するとされている。" },
  { id: 31, question: "栄養学 第1回の主なテーマは何か。", answer: "栄養の概念。", explanation: "栄養素の種類と役割、欠乏症などを扱う。" },
  { id: 32, question: "栄養学 第2回の主なテーマは何か。", answer: "エネルギー代謝1。", explanation: "三大栄養素の消化・吸収を扱う。" },
  { id: 33, question: "栄養学 第4回の主なテーマは何か。", answer: "糖質の栄養。", explanation: "シラバスに記載されている。" },
  { id: 34, question: "栄養学 第5回の主なテーマは何か。", answer: "脂質の栄養。", explanation: "シラバスに記載されている。" },
  { id: 35, question: "栄養学 第6回の主なテーマは何か。", answer: "タンパク質の栄養。", explanation: "シラバスに記載されている。" },
  { id: 36, question: "栄養学 第7回の主なテーマは何か。", answer: "ビタミンの栄養。", explanation: "シラバスに記載されている。" },
  { id: 37, question: "栄養学 第8回の主なテーマは何か。", answer: "ミネラル（無機質）の栄養。", explanation: "シラバスに記載されている。" },
  { id: 38, question: "栄養学 第9回の主なテーマは何か。", answer: "水、電解質の栄養学的意義。", explanation: "シラバスに記載されている。" },
  { id: 39, question: "栄養学 第10回の主なテーマは何か。", answer: "栄養スクリーニング・アセスメント。", explanation: "シラバスに記載されている。" },
  { id: 40, question: "栄養学 第11回の主なテーマは何か。", answer: "疾患と栄養療法（糖尿病）。", explanation: "シラバスに記載されている。" },
  { id: 41, question: "栄養学 第12回の主なテーマは何か。", answer: "疾患と栄養療法（循環器疾患・腎疾患）。", explanation: "シラバスに記載されている。" },
  { id: 42, question: "栄養学 第13回の主なテーマは何か。", answer: "疾患と栄養療法（炎症性腸疾患やオペ前後の栄養管理）。", explanation: "シラバスに記載されている。" },
  { id: 43, question: "栄養学 第14回の主なテーマは何か。", answer: "チーム医療と栄養。", explanation: "シラバスに記載されている。" },
  { id: 44, question: "栄養学 第15回の主なテーマは何か。", answer: "まとめと復習。", explanation: "シラバスに記載されている。" },
  { id: 45, question: "栄養学の教科書は何か。", answer: "羊土社『栄養科学イラストレイテッド 基礎栄養学 第5版』。", explanation: "資料の教科書・参考資料欄に記載されている。" },
  { id: 46, question: "栄養学の教科書のISBNは何か。", answer: "978-4-7581-1377-9。", explanation: "資料の教科書・参考資料欄に記載されている。" },
  { id: 47, question: "栄養学の成績評価に含まれるものは何か。", answer: "毎回の小テストと試験。", explanation: "資料の成績欄に記載されている。" },
  { id: 48, question: "栄養学のテスト受験資格として必要な出席条件は何か。", answer: "当該科目の出席回数が授業回数の3分の2以上。", explanation: "資料のテスト受験資格欄に記載されている。" },
  { id: 49, question: "遺伝形質と栄養の資料で扱われている関係は何か。", answer: "遺伝形質と栄養の相互作用。", explanation: "資料の第19・21・23ページにこのテーマが示されている。" },
  { id: 50, question: "栄養学で扱われる「エネルギー代謝2」は第何回か。", answer: "第3回。", explanation: "シラバスでは第2回がエネルギー代謝1、第3回がエネルギー代謝2。" }
];
window.NUTRITION_FLASHCARD_DATA = window.FLASHCARD_DB.nutrition;

